title: Frank Xu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aiming to apply data mining, machine learning and deep learning related techniques to obtain insights from historical and streaming data for business companies, public/environmental health services, and genomics research. 
  <br><br>
  Ph.D. Candidate in Spatial Information Science and Engineering; Ph.D. in Molecular Genetics & Biotechnology
   <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
