title: Frank Xu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

Data Science, especially Data mining, machine learning and deep learning
<br><br>
  Ph.D. Candidate in Spatial Information Science and Engineering; Ph.D. in Molecular Genetics & Biotechnology
   <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
